//go:build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AWSTag) DeepCopyInto(out *AWSTag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AWSTag.
func (in *AWSTag) DeepCopy() *AWSTag {
	if in == nil {
		return nil
	}
	out := new(AWSTag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckConfiguration) DeepCopyInto(out *HealthCheckConfiguration) {
	*out = *in
	if in.HealthyThresholdCount != nil {
		in, out := &in.HealthyThresholdCount, &out.HealthyThresholdCount
		*out = new(int32)
		**out = **in
	}
	if in.HealthCheckInterval != nil {
		in, out := &in.HealthCheckInterval, &out.HealthCheckInterval
		*out = new(int32)
		**out = **in
	}
	if in.HealthCheckPath != nil {
		in, out := &in.HealthCheckPath, &out.HealthCheckPath
		*out = new(string)
		**out = **in
	}
	if in.HealthCheckPort != nil {
		in, out := &in.HealthCheckPort, &out.HealthCheckPort
		*out = new(int32)
		**out = **in
	}
	if in.HealthCheckProtocol != nil {
		in, out := &in.HealthCheckProtocol, &out.HealthCheckProtocol
		*out = new(TargetGroupHealthCheckProtocol)
		**out = **in
	}
	if in.HealthCheckTimeout != nil {
		in, out := &in.HealthCheckTimeout, &out.HealthCheckTimeout
		*out = new(int32)
		**out = **in
	}
	if in.UnhealthyThresholdCount != nil {
		in, out := &in.UnhealthyThresholdCount, &out.UnhealthyThresholdCount
		*out = new(int32)
		**out = **in
	}
	if in.Matcher != nil {
		in, out := &in.Matcher, &out.Matcher
		*out = new(HealthCheckMatcher)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckConfiguration.
func (in *HealthCheckConfiguration) DeepCopy() *HealthCheckConfiguration {
	if in == nil {
		return nil
	}
	out := new(HealthCheckConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckMatcher) DeepCopyInto(out *HealthCheckMatcher) {
	*out = *in
	if in.HTTPCode != nil {
		in, out := &in.HTTPCode, &out.HTTPCode
		*out = new(string)
		**out = **in
	}
	if in.GRPCCode != nil {
		in, out := &in.GRPCCode, &out.GRPCCode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckMatcher.
func (in *HealthCheckMatcher) DeepCopy() *HealthCheckMatcher {
	if in == nil {
		return nil
	}
	out := new(HealthCheckMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerAttribute) DeepCopyInto(out *ListenerAttribute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerAttribute.
func (in *ListenerAttribute) DeepCopy() *ListenerAttribute {
	if in == nil {
		return nil
	}
	out := new(ListenerAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerConfiguration) DeepCopyInto(out *ListenerConfiguration) {
	*out = *in
	if in.DefaultCertificate != nil {
		in, out := &in.DefaultCertificate, &out.DefaultCertificate
		*out = new(string)
		**out = **in
	}
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SslPolicy != nil {
		in, out := &in.SslPolicy, &out.SslPolicy
		*out = new(string)
		**out = **in
	}
	if in.ALPNPolicy != nil {
		in, out := &in.ALPNPolicy, &out.ALPNPolicy
		*out = new(ALPNPolicy)
		**out = **in
	}
	if in.MutualAuthentication != nil {
		in, out := &in.MutualAuthentication, &out.MutualAuthentication
		*out = new(MutualAuthenticationAttributes)
		(*in).DeepCopyInto(*out)
	}
	if in.ListenerAttributes != nil {
		in, out := &in.ListenerAttributes, &out.ListenerAttributes
		*out = make([]ListenerAttribute, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerConfiguration.
func (in *ListenerConfiguration) DeepCopy() *ListenerConfiguration {
	if in == nil {
		return nil
	}
	out := new(ListenerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttribute) DeepCopyInto(out *LoadBalancerAttribute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttribute.
func (in *LoadBalancerAttribute) DeepCopy() *LoadBalancerAttribute {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerConfiguration) DeepCopyInto(out *LoadBalancerConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerConfiguration.
func (in *LoadBalancerConfiguration) DeepCopy() *LoadBalancerConfiguration {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerConfigurationList) DeepCopyInto(out *LoadBalancerConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerConfigurationList.
func (in *LoadBalancerConfigurationList) DeepCopy() *LoadBalancerConfigurationList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerConfigurationSpec) DeepCopyInto(out *LoadBalancerConfigurationSpec) {
	*out = *in
	if in.LoadBalancerName != nil {
		in, out := &in.LoadBalancerName, &out.LoadBalancerName
		*out = new(string)
		**out = **in
	}
	if in.Scheme != nil {
		in, out := &in.Scheme, &out.Scheme
		*out = new(LoadBalancerScheme)
		**out = **in
	}
	if in.IpAddressType != nil {
		in, out := &in.IpAddressType, &out.IpAddressType
		*out = new(LoadBalancerIpAddressType)
		**out = **in
	}
	if in.EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic != nil {
		in, out := &in.EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic, &out.EnforceSecurityGroupInboundRulesOnPrivateLinkTraffic
		*out = new(string)
		**out = **in
	}
	if in.CustomerOwnedIpv4Pool != nil {
		in, out := &in.CustomerOwnedIpv4Pool, &out.CustomerOwnedIpv4Pool
		*out = new(string)
		**out = **in
	}
	if in.IPv4IPAMPoolId != nil {
		in, out := &in.IPv4IPAMPoolId, &out.IPv4IPAMPoolId
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerSubnets != nil {
		in, out := &in.LoadBalancerSubnets, &out.LoadBalancerSubnets
		*out = new([]SubnetConfiguration)
		if **in != nil {
			in, out := *in, *out
			*out = make([]SubnetConfiguration, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.LoadBalancerSubnetsSelector != nil {
		in, out := &in.LoadBalancerSubnetsSelector, &out.LoadBalancerSubnetsSelector
		*out = new(map[string][]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string][]string, len(*in))
			for key, val := range *in {
				var outVal []string
				if val == nil {
					(*out)[key] = nil
				} else {
					inVal := (*in)[key]
					in, out := &inVal, &outVal
					*out = make([]string, len(*in))
					copy(*out, *in)
				}
				(*out)[key] = outVal
			}
		}
	}
	if in.ListenerConfigurations != nil {
		in, out := &in.ListenerConfigurations, &out.ListenerConfigurations
		*out = new([]ListenerConfiguration)
		if **in != nil {
			in, out := *in, *out
			*out = make([]ListenerConfiguration, len(*in))
			for i := range *in {
				(*in)[i].DeepCopyInto(&(*out)[i])
			}
		}
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.SecurityGroupPrefixes != nil {
		in, out := &in.SecurityGroupPrefixes, &out.SecurityGroupPrefixes
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.SourceRanges != nil {
		in, out := &in.SourceRanges, &out.SourceRanges
		*out = new([]string)
		if **in != nil {
			in, out := *in, *out
			*out = make([]string, len(*in))
			copy(*out, *in)
		}
	}
	if in.VpcId != nil {
		in, out := &in.VpcId, &out.VpcId
		*out = new(string)
		**out = **in
	}
	if in.LoadBalancerAttributes != nil {
		in, out := &in.LoadBalancerAttributes, &out.LoadBalancerAttributes
		*out = make([]LoadBalancerAttribute, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]AWSTag, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerConfigurationSpec.
func (in *LoadBalancerConfigurationSpec) DeepCopy() *LoadBalancerConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerConfigurationStatus) DeepCopyInto(out *LoadBalancerConfigurationStatus) {
	*out = *in
	if in.ObservedGatewayConfigurationGeneration != nil {
		in, out := &in.ObservedGatewayConfigurationGeneration, &out.ObservedGatewayConfigurationGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ObservedGatewayClassConfigurationGeneration != nil {
		in, out := &in.ObservedGatewayClassConfigurationGeneration, &out.ObservedGatewayClassConfigurationGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerConfigurationStatus.
func (in *LoadBalancerConfigurationStatus) DeepCopy() *LoadBalancerConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MutualAuthenticationAttributes) DeepCopyInto(out *MutualAuthenticationAttributes) {
	*out = *in
	if in.AdvertiseTrustStoreCaNames != nil {
		in, out := &in.AdvertiseTrustStoreCaNames, &out.AdvertiseTrustStoreCaNames
		*out = new(AdvertiseTrustStoreCaNamesEnum)
		**out = **in
	}
	if in.IgnoreClientCertificateExpiry != nil {
		in, out := &in.IgnoreClientCertificateExpiry, &out.IgnoreClientCertificateExpiry
		*out = new(bool)
		**out = **in
	}
	if in.TrustStore != nil {
		in, out := &in.TrustStore, &out.TrustStore
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MutualAuthenticationAttributes.
func (in *MutualAuthenticationAttributes) DeepCopy() *MutualAuthenticationAttributes {
	if in == nil {
		return nil
	}
	out := new(MutualAuthenticationAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Reference) DeepCopyInto(out *Reference) {
	*out = *in
	if in.Group != nil {
		in, out := &in.Group, &out.Group
		*out = new(string)
		**out = **in
	}
	if in.Kind != nil {
		in, out := &in.Kind, &out.Kind
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Reference.
func (in *Reference) DeepCopy() *Reference {
	if in == nil {
		return nil
	}
	out := new(Reference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RouteConfiguration) DeepCopyInto(out *RouteConfiguration) {
	*out = *in
	in.TargetGroupProps.DeepCopyInto(&out.TargetGroupProps)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RouteConfiguration.
func (in *RouteConfiguration) DeepCopy() *RouteConfiguration {
	if in == nil {
		return nil
	}
	out := new(RouteConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetConfiguration) DeepCopyInto(out *SubnetConfiguration) {
	*out = *in
	if in.EIPAllocation != nil {
		in, out := &in.EIPAllocation, &out.EIPAllocation
		*out = new(string)
		**out = **in
	}
	if in.PrivateIPv4Allocation != nil {
		in, out := &in.PrivateIPv4Allocation, &out.PrivateIPv4Allocation
		*out = new(string)
		**out = **in
	}
	if in.IPv6Allocation != nil {
		in, out := &in.IPv6Allocation, &out.IPv6Allocation
		*out = new(string)
		**out = **in
	}
	if in.SourceNatIPv6Prefix != nil {
		in, out := &in.SourceNatIPv6Prefix, &out.SourceNatIPv6Prefix
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetConfiguration.
func (in *SubnetConfiguration) DeepCopy() *SubnetConfiguration {
	if in == nil {
		return nil
	}
	out := new(SubnetConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Tag) DeepCopyInto(out *Tag) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Tag.
func (in *Tag) DeepCopy() *Tag {
	if in == nil {
		return nil
	}
	out := new(Tag)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupAttribute) DeepCopyInto(out *TargetGroupAttribute) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupAttribute.
func (in *TargetGroupAttribute) DeepCopy() *TargetGroupAttribute {
	if in == nil {
		return nil
	}
	out := new(TargetGroupAttribute)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupConfiguration) DeepCopyInto(out *TargetGroupConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupConfiguration.
func (in *TargetGroupConfiguration) DeepCopy() *TargetGroupConfiguration {
	if in == nil {
		return nil
	}
	out := new(TargetGroupConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TargetGroupConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupConfigurationList) DeepCopyInto(out *TargetGroupConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TargetGroupConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupConfigurationList.
func (in *TargetGroupConfigurationList) DeepCopy() *TargetGroupConfigurationList {
	if in == nil {
		return nil
	}
	out := new(TargetGroupConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TargetGroupConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupConfigurationSpec) DeepCopyInto(out *TargetGroupConfigurationSpec) {
	*out = *in
	in.TargetReference.DeepCopyInto(&out.TargetReference)
	in.DefaultConfiguration.DeepCopyInto(&out.DefaultConfiguration)
	if in.RouteConfigurations != nil {
		in, out := &in.RouteConfigurations, &out.RouteConfigurations
		*out = make([]RouteConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupConfigurationSpec.
func (in *TargetGroupConfigurationSpec) DeepCopy() *TargetGroupConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(TargetGroupConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupConfigurationStatus) DeepCopyInto(out *TargetGroupConfigurationStatus) {
	*out = *in
	if in.ObservedGatewayConfigurationGeneration != nil {
		in, out := &in.ObservedGatewayConfigurationGeneration, &out.ObservedGatewayConfigurationGeneration
		*out = new(int64)
		**out = **in
	}
	if in.ObservedGatewayClassConfigurationGeneration != nil {
		in, out := &in.ObservedGatewayClassConfigurationGeneration, &out.ObservedGatewayClassConfigurationGeneration
		*out = new(int64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupConfigurationStatus.
func (in *TargetGroupConfigurationStatus) DeepCopy() *TargetGroupConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(TargetGroupConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupProps) DeepCopyInto(out *TargetGroupProps) {
	*out = *in
	if in.IPAddressType != nil {
		in, out := &in.IPAddressType, &out.IPAddressType
		*out = new(TargetGroupIPAddressType)
		**out = **in
	}
	if in.HealthCheckConfig != nil {
		in, out := &in.HealthCheckConfig, &out.HealthCheckConfig
		*out = new(HealthCheckConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	if in.TargetGroupAttributes != nil {
		in, out := &in.TargetGroupAttributes, &out.TargetGroupAttributes
		*out = make([]TargetGroupAttribute, len(*in))
		copy(*out, *in)
	}
	if in.TargetType != nil {
		in, out := &in.TargetType, &out.TargetType
		*out = new(TargetType)
		**out = **in
	}
	if in.ProtocolVersion != nil {
		in, out := &in.ProtocolVersion, &out.ProtocolVersion
		*out = new(ProtocolVersion)
		**out = **in
	}
	if in.VpcID != nil {
		in, out := &in.VpcID, &out.VpcID
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]Tag, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupProps.
func (in *TargetGroupProps) DeepCopy() *TargetGroupProps {
	if in == nil {
		return nil
	}
	out := new(TargetGroupProps)
	in.DeepCopyInto(out)
	return out
}
