resources:
- gateway.networking.k8s.io_referencegrants.yaml
- gateway.networking.k8s.io_tcproutes.yaml
- gateway.networking.k8s.io_tlsroutes.yaml
- gateway.networking.k8s.io_udproutes.yaml
- gateway.networking.k8s.io_vap_safeupgrades.yaml