apiVersion: v1
kind: Service
metadata:
{{- if .Values.defaultBackend.service.annotations }}
  annotations:
{{ toYaml .Values.defaultBackend.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: default-backend
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  {{- if .Values.defaultBackend.service.labels }}
{{ toYaml .Values.defaultBackend.service.labels | indent 4 }}
  {{- end }}
  name: {{ template "defaultBackend.fullname" . }}
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: {{ template "name" . }}
    component: default-backend
    release: {{ .Release.Name }}
