{{- if .Values.newImagePullSecret.name }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.newImagePullSecret.value }}
kind: Secret
metadata:
  name: {{ .Values.newImagePullSecret.name }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
{{- end }}

