apiVersion: gateway.networking.k8s.io/v1
date: "2025-12-22T13:25:07-08:00"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.3.0
implementation:
  contact:
  - https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/main/OWNERS#L6
  organization: aws
  project: aws-load-balancer-controller
  url: https://github.com/kubernetes-sigs/aws-load-balancer-controller
  version: v2.17.0
kind: ConformanceReport
mode: default
profiles:
- core:
    result: partial
    skippedTests:
    - GatewayInvalidTLSConfiguration
    - GatewaySecretInvalidReferenceGrant
    - GatewaySecretMissingReferenceGrant
    - GatewaySecretReferenceGrantAllInNamespace
    - GatewaySecretReferenceGrantSpecific
    - GatewayWithAttachedRoutes
    - HTTPRouteHTTPSListener
    - HTTPRouteHostnameIntersection
    - HTTPRouteRequestHeaderModifier
    - HTTPRouteServiceTypes
    statistics:
      Failed: 0
      Passed: 23
      Skipped: 10
  extended:
    result: success
    statistics:
      Failed: 0
      Passed: 5
      Skipped: 0
    supportedFeatures:
    - HTTPRouteDestinationPortMatching
    - HTTPRouteMethodMatching
    - HTTPRouteParentRefPort
    - HTTPRoutePortRedirect
    unsupportedFeatures:
    - GatewayAddressEmpty
    - GatewayHTTPListenerIsolation
    - GatewayInfrastructurePropagation
    - GatewayPort8080
    - GatewayStaticAddresses
    - HTTPRouteBackendProtocolH2C
    - HTTPRouteBackendProtocolWebSocket
    - HTTPRouteBackendRequestHeaderModification
    - HTTPRouteBackendTimeout
    - HTTPRouteHostRewrite
    - HTTPRoutePathRedirect
    - HTTPRoutePathRewrite
    - HTTPRouteQueryParamMatching
    - HTTPRouteRequestMirror
    - HTTPRouteRequestMultipleMirrors
    - HTTPRouteRequestPercentageMirror
    - HTTPRouteRequestTimeout
    - HTTPRouteResponseHeaderModification
    - HTTPRouteSchemeRedirect
  name: GATEWAY-HTTP
  summary: Core tests partially succeeded with 10 test skips. Extended tests succeeded.
