// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import elbv2 "github.com/aws/aws-sdk-go/service/elbv2"
import mock "github.com/stretchr/testify/mock"
import v1beta1 "k8s.io/api/extensions/v1beta1"

// EndpointResolver is an autogenerated mock type for the EndpointResolver type
type EndpointResolver struct {
	mock.Mock
}

// Resolve provides a mock function with given fields: ingress, _a1
func (_m *EndpointResolver) Resolve(ingress *v1beta1.Ingress, _a1 *v1beta1.IngressBackend) ([]*elbv2.TargetDescription, error) {
	ret := _m.Called(ingress, _a1)

	var r0 []*elbv2.TargetDescription
	if rf, ok := ret.Get(0).(func(*v1beta1.Ingress, *v1beta1.IngressBackend) []*elbv2.TargetDescription); ok {
		r0 = rf(ingress, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*elbv2.TargetDescription)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*v1beta1.Ingress, *v1beta1.IngressBackend) error); ok {
		r1 = rf(ingress, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
