// +build !ignore_autogenerated

/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticateCognitoConfig) DeepCopyInto(out *AuthenticateCognitoConfig) {
	*out = *in
	in.AuthenticateConfig.DeepCopyInto(&out.AuthenticateConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticateCognitoConfig.
func (in *AuthenticateCognitoConfig) DeepCopy() *AuthenticateCognitoConfig {
	if in == nil {
		return nil
	}
	out := new(AuthenticateCognitoConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticateConfig) DeepCopyInto(out *AuthenticateConfig) {
	*out = *in
	if in.AuthenticationRequestExtraParams != nil {
		in, out := &in.AuthenticationRequestExtraParams, &out.AuthenticationRequestExtraParams
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticateConfig.
func (in *AuthenticateConfig) DeepCopy() *AuthenticateConfig {
	if in == nil {
		return nil
	}
	out := new(AuthenticateConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthenticateOIDCConfig) DeepCopyInto(out *AuthenticateOIDCConfig) {
	*out = *in
	in.AuthenticateConfig.DeepCopyInto(&out.AuthenticateConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthenticateOIDCConfig.
func (in *AuthenticateOIDCConfig) DeepCopy() *AuthenticateOIDCConfig {
	if in == nil {
		return nil
	}
	out := new(AuthenticateOIDCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointBinding) DeepCopyInto(out *EndpointBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointBinding.
func (in *EndpointBinding) DeepCopy() *EndpointBinding {
	if in == nil {
		return nil
	}
	out := new(EndpointBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointBindingList) DeepCopyInto(out *EndpointBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EndpointBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointBindingList.
func (in *EndpointBindingList) DeepCopy() *EndpointBindingList {
	if in == nil {
		return nil
	}
	out := new(EndpointBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointBindingSpec) DeepCopyInto(out *EndpointBindingSpec) {
	*out = *in
	out.TargetGroup = in.TargetGroup
	out.ServiceRef = in.ServiceRef
	out.ServicePort = in.ServicePort
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointBindingSpec.
func (in *EndpointBindingSpec) DeepCopy() *EndpointBindingSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointBindingStatus) DeepCopyInto(out *EndpointBindingStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointBindingStatus.
func (in *EndpointBindingStatus) DeepCopy() *EndpointBindingStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FixedResponseConfig) DeepCopyInto(out *FixedResponseConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FixedResponseConfig.
func (in *FixedResponseConfig) DeepCopy() *FixedResponseConfig {
	if in == nil {
		return nil
	}
	out := new(FixedResponseConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ForwardConfig) DeepCopyInto(out *ForwardConfig) {
	*out = *in
	out.TargetGroup = in.TargetGroup
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ForwardConfig.
func (in *ForwardConfig) DeepCopy() *ForwardConfig {
	if in == nil {
		return nil
	}
	out := new(ForwardConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckConfig) DeepCopyInto(out *HealthCheckConfig) {
	*out = *in
	out.Port = in.Port
	out.Matcher = in.Matcher
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckConfig.
func (in *HealthCheckConfig) DeepCopy() *HealthCheckConfig {
	if in == nil {
		return nil
	}
	out := new(HealthCheckConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthCheckMatcher) DeepCopyInto(out *HealthCheckMatcher) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthCheckMatcher.
func (in *HealthCheckMatcher) DeepCopy() *HealthCheckMatcher {
	if in == nil {
		return nil
	}
	out := new(HealthCheckMatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HostHeaderConditionConfig) DeepCopyInto(out *HostHeaderConditionConfig) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostHeaderConditionConfig.
func (in *HostHeaderConditionConfig) DeepCopy() *HostHeaderConditionConfig {
	if in == nil {
		return nil
	}
	out := new(HostHeaderConditionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IPPermission) DeepCopyInto(out *IPPermission) {
	*out = *in
	out.IPProtocol = in.IPProtocol
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IPPermission.
func (in *IPPermission) DeepCopy() *IPPermission {
	if in == nil {
		return nil
	}
	out := new(IPPermission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LBCookieConfig) DeepCopyInto(out *LBCookieConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LBCookieConfig.
func (in *LBCookieConfig) DeepCopy() *LBCookieConfig {
	if in == nil {
		return nil
	}
	out := new(LBCookieConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Listener) DeepCopyInto(out *Listener) {
	*out = *in
	if in.Certificates != nil {
		in, out := &in.Certificates, &out.Certificates
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DefaultActions != nil {
		in, out := &in.DefaultActions, &out.DefaultActions
		*out = make([]ListenerAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Rules != nil {
		in, out := &in.Rules, &out.Rules
		*out = make([]ListenerRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Listener.
func (in *Listener) DeepCopy() *Listener {
	if in == nil {
		return nil
	}
	out := new(Listener)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerAction) DeepCopyInto(out *ListenerAction) {
	*out = *in
	if in.AuthenticateCognito != nil {
		in, out := &in.AuthenticateCognito, &out.AuthenticateCognito
		*out = new(AuthenticateCognitoConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthenticateOIDC != nil {
		in, out := &in.AuthenticateOIDC, &out.AuthenticateOIDC
		*out = new(AuthenticateOIDCConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.FixedResponse != nil {
		in, out := &in.FixedResponse, &out.FixedResponse
		*out = new(FixedResponseConfig)
		**out = **in
	}
	if in.Redirect != nil {
		in, out := &in.Redirect, &out.Redirect
		*out = new(RedirectConfig)
		**out = **in
	}
	if in.Forward != nil {
		in, out := &in.Forward, &out.Forward
		*out = new(ForwardConfig)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerAction.
func (in *ListenerAction) DeepCopy() *ListenerAction {
	if in == nil {
		return nil
	}
	out := new(ListenerAction)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerRule) DeepCopyInto(out *ListenerRule) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ListenerRuleCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Actions != nil {
		in, out := &in.Actions, &out.Actions
		*out = make([]ListenerAction, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerRule.
func (in *ListenerRule) DeepCopy() *ListenerRule {
	if in == nil {
		return nil
	}
	out := new(ListenerRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ListenerRuleCondition) DeepCopyInto(out *ListenerRuleCondition) {
	*out = *in
	if in.HostHeader != nil {
		in, out := &in.HostHeader, &out.HostHeader
		*out = new(HostHeaderConditionConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.PathPattern != nil {
		in, out := &in.PathPattern, &out.PathPattern
		*out = new(PathPatternConditionConfig)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ListenerRuleCondition.
func (in *ListenerRuleCondition) DeepCopy() *ListenerRuleCondition {
	if in == nil {
		return nil
	}
	out := new(ListenerRuleCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancer) DeepCopyInto(out *LoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancer.
func (in *LoadBalancer) DeepCopy() *LoadBalancer {
	if in == nil {
		return nil
	}
	out := new(LoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAccessLogsAttributes) DeepCopyInto(out *LoadBalancerAccessLogsAttributes) {
	*out = *in
	out.S3 = in.S3
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAccessLogsAttributes.
func (in *LoadBalancerAccessLogsAttributes) DeepCopy() *LoadBalancerAccessLogsAttributes {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAccessLogsAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAccessLogsS3Attributes) DeepCopyInto(out *LoadBalancerAccessLogsS3Attributes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAccessLogsS3Attributes.
func (in *LoadBalancerAccessLogsS3Attributes) DeepCopy() *LoadBalancerAccessLogsS3Attributes {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAccessLogsS3Attributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAttributes) DeepCopyInto(out *LoadBalancerAttributes) {
	*out = *in
	out.DeletionProtection = in.DeletionProtection
	out.AccessLogs = in.AccessLogs
	out.IdleTimeout = in.IdleTimeout
	out.Routing = in.Routing
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAttributes.
func (in *LoadBalancerAttributes) DeepCopy() *LoadBalancerAttributes {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerDeletionProtectionAttributes) DeepCopyInto(out *LoadBalancerDeletionProtectionAttributes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerDeletionProtectionAttributes.
func (in *LoadBalancerDeletionProtectionAttributes) DeepCopy() *LoadBalancerDeletionProtectionAttributes {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerDeletionProtectionAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerIdleTimeoutAttributes) DeepCopyInto(out *LoadBalancerIdleTimeoutAttributes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerIdleTimeoutAttributes.
func (in *LoadBalancerIdleTimeoutAttributes) DeepCopy() *LoadBalancerIdleTimeoutAttributes {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerIdleTimeoutAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerList) DeepCopyInto(out *LoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerList.
func (in *LoadBalancerList) DeepCopy() *LoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerRoutingAttributes) DeepCopyInto(out *LoadBalancerRoutingAttributes) {
	*out = *in
	out.HTTP2 = in.HTTP2
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerRoutingAttributes.
func (in *LoadBalancerRoutingAttributes) DeepCopy() *LoadBalancerRoutingAttributes {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerRoutingAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerRoutingHTTP2Attributes) DeepCopyInto(out *LoadBalancerRoutingHTTP2Attributes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerRoutingHTTP2Attributes.
func (in *LoadBalancerRoutingHTTP2Attributes) DeepCopy() *LoadBalancerRoutingHTTP2Attributes {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerRoutingHTTP2Attributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerSpec) DeepCopyInto(out *LoadBalancerSpec) {
	*out = *in
	if in.SubnetMappings != nil {
		in, out := &in.SubnetMappings, &out.SubnetMappings
		*out = make([]SubnetMapping, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]SecurityGroupReference, len(*in))
		copy(*out, *in)
	}
	out.Attributes = in.Attributes
	if in.Listeners != nil {
		in, out := &in.Listeners, &out.Listeners
		*out = make([]Listener, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerSpec.
func (in *LoadBalancerSpec) DeepCopy() *LoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerStatus) DeepCopyInto(out *LoadBalancerStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerStatus.
func (in *LoadBalancerStatus) DeepCopy() *LoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PathPatternConditionConfig) DeepCopyInto(out *PathPatternConditionConfig) {
	*out = *in
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PathPatternConditionConfig.
func (in *PathPatternConditionConfig) DeepCopy() *PathPatternConditionConfig {
	if in == nil {
		return nil
	}
	out := new(PathPatternConditionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RedirectConfig) DeepCopyInto(out *RedirectConfig) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RedirectConfig.
func (in *RedirectConfig) DeepCopy() *RedirectConfig {
	if in == nil {
		return nil
	}
	out := new(RedirectConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroup) DeepCopyInto(out *SecurityGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroup.
func (in *SecurityGroup) DeepCopy() *SecurityGroup {
	if in == nil {
		return nil
	}
	out := new(SecurityGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupList) DeepCopyInto(out *SecurityGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecurityGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupList.
func (in *SecurityGroupList) DeepCopy() *SecurityGroupList {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SecurityGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupReference) DeepCopyInto(out *SecurityGroupReference) {
	*out = *in
	out.SecurityGroupRef = in.SecurityGroupRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupReference.
func (in *SecurityGroupReference) DeepCopy() *SecurityGroupReference {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupSpec) DeepCopyInto(out *SecurityGroupSpec) {
	*out = *in
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make([]IPPermission, len(*in))
		copy(*out, *in)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupSpec.
func (in *SecurityGroupSpec) DeepCopy() *SecurityGroupSpec {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityGroupStatus) DeepCopyInto(out *SecurityGroupStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityGroupStatus.
func (in *SecurityGroupStatus) DeepCopy() *SecurityGroupStatus {
	if in == nil {
		return nil
	}
	out := new(SecurityGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SubnetMapping) DeepCopyInto(out *SubnetMapping) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SubnetMapping.
func (in *SubnetMapping) DeepCopy() *SubnetMapping {
	if in == nil {
		return nil
	}
	out := new(SubnetMapping)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroup) DeepCopyInto(out *TargetGroup) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroup.
func (in *TargetGroup) DeepCopy() *TargetGroup {
	if in == nil {
		return nil
	}
	out := new(TargetGroup)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TargetGroup) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupAttributes) DeepCopyInto(out *TargetGroupAttributes) {
	*out = *in
	out.DeregistrationDelay = in.DeregistrationDelay
	out.SlowStart = in.SlowStart
	out.Stickiness = in.Stickiness
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupAttributes.
func (in *TargetGroupAttributes) DeepCopy() *TargetGroupAttributes {
	if in == nil {
		return nil
	}
	out := new(TargetGroupAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupDeregistrationDelayAttributes) DeepCopyInto(out *TargetGroupDeregistrationDelayAttributes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupDeregistrationDelayAttributes.
func (in *TargetGroupDeregistrationDelayAttributes) DeepCopy() *TargetGroupDeregistrationDelayAttributes {
	if in == nil {
		return nil
	}
	out := new(TargetGroupDeregistrationDelayAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupList) DeepCopyInto(out *TargetGroupList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TargetGroup, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupList.
func (in *TargetGroupList) DeepCopy() *TargetGroupList {
	if in == nil {
		return nil
	}
	out := new(TargetGroupList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TargetGroupList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupReference) DeepCopyInto(out *TargetGroupReference) {
	*out = *in
	out.TargetGroupRef = in.TargetGroupRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupReference.
func (in *TargetGroupReference) DeepCopy() *TargetGroupReference {
	if in == nil {
		return nil
	}
	out := new(TargetGroupReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupSlowStartAttributes) DeepCopyInto(out *TargetGroupSlowStartAttributes) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupSlowStartAttributes.
func (in *TargetGroupSlowStartAttributes) DeepCopy() *TargetGroupSlowStartAttributes {
	if in == nil {
		return nil
	}
	out := new(TargetGroupSlowStartAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupSpec) DeepCopyInto(out *TargetGroupSpec) {
	*out = *in
	out.HealthCheckConfig = in.HealthCheckConfig
	out.Attributes = in.Attributes
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupSpec.
func (in *TargetGroupSpec) DeepCopy() *TargetGroupSpec {
	if in == nil {
		return nil
	}
	out := new(TargetGroupSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupStatus) DeepCopyInto(out *TargetGroupStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupStatus.
func (in *TargetGroupStatus) DeepCopy() *TargetGroupStatus {
	if in == nil {
		return nil
	}
	out := new(TargetGroupStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetGroupStickinessAttributes) DeepCopyInto(out *TargetGroupStickinessAttributes) {
	*out = *in
	out.LBCookie = in.LBCookie
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetGroupStickinessAttributes.
func (in *TargetGroupStickinessAttributes) DeepCopy() *TargetGroupStickinessAttributes {
	if in == nil {
		return nil
	}
	out := new(TargetGroupStickinessAttributes)
	in.DeepCopyInto(out)
	return out
}
