// Code generated by MockGen. DO NOT EDIT.
// Source: sigs.k8s.io/aws-load-balancer-controller/v3/pkg/aws/services (interfaces: CloudWatchLogs)

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	cloudwatchlogs "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs"
	types "github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs/types"
	gomock "github.com/golang/mock/gomock"
)

// MockCloudWatchLogs is a mock of CloudWatchLogs interface.
type MockCloudWatchLogs struct {
	ctrl     *gomock.Controller
	recorder *MockCloudWatchLogsMockRecorder
}

// MockCloudWatchLogsMockRecorder is the mock recorder for MockCloudWatchLogs.
type MockCloudWatchLogsMockRecorder struct {
	mock *MockCloudWatchLogs
}

// NewMockCloudWatchLogs creates a new mock instance.
func NewMockCloudWatchLogs(ctrl *gomock.Controller) *MockCloudWatchLogs {
	mock := &MockCloudWatchLogs{ctrl: ctrl}
	mock.recorder = &MockCloudWatchLogsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudWatchLogs) EXPECT() *MockCloudWatchLogsMockRecorder {
	return m.recorder
}

// CreateDeliveryWithContext mocks base method.
func (m *MockCloudWatchLogs) CreateDeliveryWithContext(arg0 context.Context, arg1 *cloudwatchlogs.CreateDeliveryInput) (*cloudwatchlogs.CreateDeliveryOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeliveryWithContext", arg0, arg1)
	ret0, _ := ret[0].(*cloudwatchlogs.CreateDeliveryOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDeliveryWithContext indicates an expected call of CreateDeliveryWithContext.
func (mr *MockCloudWatchLogsMockRecorder) CreateDeliveryWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeliveryWithContext", reflect.TypeOf((*MockCloudWatchLogs)(nil).CreateDeliveryWithContext), arg0, arg1)
}

// DeleteDeliveryDestinationWithContext mocks base method.
func (m *MockCloudWatchLogs) DeleteDeliveryDestinationWithContext(arg0 context.Context, arg1 *cloudwatchlogs.DeleteDeliveryDestinationInput) (*cloudwatchlogs.DeleteDeliveryDestinationOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeliveryDestinationWithContext", arg0, arg1)
	ret0, _ := ret[0].(*cloudwatchlogs.DeleteDeliveryDestinationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDeliveryDestinationWithContext indicates an expected call of DeleteDeliveryDestinationWithContext.
func (mr *MockCloudWatchLogsMockRecorder) DeleteDeliveryDestinationWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeliveryDestinationWithContext", reflect.TypeOf((*MockCloudWatchLogs)(nil).DeleteDeliveryDestinationWithContext), arg0, arg1)
}

// DeleteDeliverySourceWithContext mocks base method.
func (m *MockCloudWatchLogs) DeleteDeliverySourceWithContext(arg0 context.Context, arg1 *cloudwatchlogs.DeleteDeliverySourceInput) (*cloudwatchlogs.DeleteDeliverySourceOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeliverySourceWithContext", arg0, arg1)
	ret0, _ := ret[0].(*cloudwatchlogs.DeleteDeliverySourceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDeliverySourceWithContext indicates an expected call of DeleteDeliverySourceWithContext.
func (mr *MockCloudWatchLogsMockRecorder) DeleteDeliverySourceWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeliverySourceWithContext", reflect.TypeOf((*MockCloudWatchLogs)(nil).DeleteDeliverySourceWithContext), arg0, arg1)
}

// DeleteDeliveryWithContext mocks base method.
func (m *MockCloudWatchLogs) DeleteDeliveryWithContext(arg0 context.Context, arg1 *cloudwatchlogs.DeleteDeliveryInput) (*cloudwatchlogs.DeleteDeliveryOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDeliveryWithContext", arg0, arg1)
	ret0, _ := ret[0].(*cloudwatchlogs.DeleteDeliveryOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDeliveryWithContext indicates an expected call of DeleteDeliveryWithContext.
func (mr *MockCloudWatchLogsMockRecorder) DeleteDeliveryWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDeliveryWithContext", reflect.TypeOf((*MockCloudWatchLogs)(nil).DeleteDeliveryWithContext), arg0, arg1)
}

// DescribeDeliveriesAsList mocks base method.
func (m *MockCloudWatchLogs) DescribeDeliveriesAsList(arg0 context.Context, arg1 *cloudwatchlogs.DescribeDeliveriesInput) ([]types.Delivery, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDeliveriesAsList", arg0, arg1)
	ret0, _ := ret[0].([]types.Delivery)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDeliveriesAsList indicates an expected call of DescribeDeliveriesAsList.
func (mr *MockCloudWatchLogsMockRecorder) DescribeDeliveriesAsList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDeliveriesAsList", reflect.TypeOf((*MockCloudWatchLogs)(nil).DescribeDeliveriesAsList), arg0, arg1)
}

// DescribeDeliveryDestinationsAsList mocks base method.
func (m *MockCloudWatchLogs) DescribeDeliveryDestinationsAsList(arg0 context.Context, arg1 *cloudwatchlogs.DescribeDeliveryDestinationsInput) ([]types.DeliveryDestination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDeliveryDestinationsAsList", arg0, arg1)
	ret0, _ := ret[0].([]types.DeliveryDestination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDeliveryDestinationsAsList indicates an expected call of DescribeDeliveryDestinationsAsList.
func (mr *MockCloudWatchLogsMockRecorder) DescribeDeliveryDestinationsAsList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDeliveryDestinationsAsList", reflect.TypeOf((*MockCloudWatchLogs)(nil).DescribeDeliveryDestinationsAsList), arg0, arg1)
}

// DescribeDeliverySourcesAsList mocks base method.
func (m *MockCloudWatchLogs) DescribeDeliverySourcesAsList(arg0 context.Context, arg1 *cloudwatchlogs.DescribeDeliverySourcesInput) ([]types.DeliverySource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeDeliverySourcesAsList", arg0, arg1)
	ret0, _ := ret[0].([]types.DeliverySource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeDeliverySourcesAsList indicates an expected call of DescribeDeliverySourcesAsList.
func (mr *MockCloudWatchLogsMockRecorder) DescribeDeliverySourcesAsList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeDeliverySourcesAsList", reflect.TypeOf((*MockCloudWatchLogs)(nil).DescribeDeliverySourcesAsList), arg0, arg1)
}

// PutDeliveryDestinationWithContext mocks base method.
func (m *MockCloudWatchLogs) PutDeliveryDestinationWithContext(arg0 context.Context, arg1 *cloudwatchlogs.PutDeliveryDestinationInput) (*cloudwatchlogs.PutDeliveryDestinationOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutDeliveryDestinationWithContext", arg0, arg1)
	ret0, _ := ret[0].(*cloudwatchlogs.PutDeliveryDestinationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutDeliveryDestinationWithContext indicates an expected call of PutDeliveryDestinationWithContext.
func (mr *MockCloudWatchLogsMockRecorder) PutDeliveryDestinationWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutDeliveryDestinationWithContext", reflect.TypeOf((*MockCloudWatchLogs)(nil).PutDeliveryDestinationWithContext), arg0, arg1)
}

// PutDeliverySourceWithContext mocks base method.
func (m *MockCloudWatchLogs) PutDeliverySourceWithContext(arg0 context.Context, arg1 *cloudwatchlogs.PutDeliverySourceInput) (*cloudwatchlogs.PutDeliverySourceOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutDeliverySourceWithContext", arg0, arg1)
	ret0, _ := ret[0].(*cloudwatchlogs.PutDeliverySourceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutDeliverySourceWithContext indicates an expected call of PutDeliverySourceWithContext.
func (mr *MockCloudWatchLogsMockRecorder) PutDeliverySourceWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutDeliverySourceWithContext", reflect.TypeOf((*MockCloudWatchLogs)(nil).PutDeliverySourceWithContext), arg0, arg1)
}

// UpdateDeliveryConfigurationWithContext mocks base method.
func (m *MockCloudWatchLogs) UpdateDeliveryConfigurationWithContext(arg0 context.Context, arg1 *cloudwatchlogs.UpdateDeliveryConfigurationInput) (*cloudwatchlogs.UpdateDeliveryConfigurationOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeliveryConfigurationWithContext", arg0, arg1)
	ret0, _ := ret[0].(*cloudwatchlogs.UpdateDeliveryConfigurationOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDeliveryConfigurationWithContext indicates an expected call of UpdateDeliveryConfigurationWithContext.
func (mr *MockCloudWatchLogsMockRecorder) UpdateDeliveryConfigurationWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeliveryConfigurationWithContext", reflect.TypeOf((*MockCloudWatchLogs)(nil).UpdateDeliveryConfigurationWithContext), arg0, arg1)
}
