// Code generated by MockGen. DO NOT EDIT.
// Source: sigs.k8s.io/aws-load-balancer-controller/pkg/aws/services (interfaces: GlobalAccelerator)

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	globalaccelerator "github.com/aws/aws-sdk-go-v2/service/globalaccelerator"
	types "github.com/aws/aws-sdk-go-v2/service/globalaccelerator/types"
	gomock "github.com/golang/mock/gomock"
)

// MockGlobalAccelerator is a mock of GlobalAccelerator interface.
type MockGlobalAccelerator struct {
	ctrl     *gomock.Controller
	recorder *MockGlobalAcceleratorMockRecorder
}

// MockGlobalAcceleratorMockRecorder is the mock recorder for MockGlobalAccelerator.
type MockGlobalAcceleratorMockRecorder struct {
	mock *MockGlobalAccelerator
}

// NewMockGlobalAccelerator creates a new mock instance.
func NewMockGlobalAccelerator(ctrl *gomock.Controller) *MockGlobalAccelerator {
	mock := &MockGlobalAccelerator{ctrl: ctrl}
	mock.recorder = &MockGlobalAcceleratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGlobalAccelerator) EXPECT() *MockGlobalAcceleratorMockRecorder {
	return m.recorder
}

// CreateAcceleratorWithContext mocks base method.
func (m *MockGlobalAccelerator) CreateAcceleratorWithContext(arg0 context.Context, arg1 *globalaccelerator.CreateAcceleratorInput) (*globalaccelerator.CreateAcceleratorOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAcceleratorWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.CreateAcceleratorOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAcceleratorWithContext indicates an expected call of CreateAcceleratorWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) CreateAcceleratorWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAcceleratorWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).CreateAcceleratorWithContext), arg0, arg1)
}

// CreateEndpointGroupWithContext mocks base method.
func (m *MockGlobalAccelerator) CreateEndpointGroupWithContext(arg0 context.Context, arg1 *globalaccelerator.CreateEndpointGroupInput) (*globalaccelerator.CreateEndpointGroupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEndpointGroupWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.CreateEndpointGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEndpointGroupWithContext indicates an expected call of CreateEndpointGroupWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) CreateEndpointGroupWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEndpointGroupWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).CreateEndpointGroupWithContext), arg0, arg1)
}

// CreateListenerWithContext mocks base method.
func (m *MockGlobalAccelerator) CreateListenerWithContext(arg0 context.Context, arg1 *globalaccelerator.CreateListenerInput) (*globalaccelerator.CreateListenerOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateListenerWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.CreateListenerOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateListenerWithContext indicates an expected call of CreateListenerWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) CreateListenerWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateListenerWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).CreateListenerWithContext), arg0, arg1)
}

// DeleteAcceleratorWithContext mocks base method.
func (m *MockGlobalAccelerator) DeleteAcceleratorWithContext(arg0 context.Context, arg1 *globalaccelerator.DeleteAcceleratorInput) (*globalaccelerator.DeleteAcceleratorOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAcceleratorWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.DeleteAcceleratorOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAcceleratorWithContext indicates an expected call of DeleteAcceleratorWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) DeleteAcceleratorWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAcceleratorWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).DeleteAcceleratorWithContext), arg0, arg1)
}

// DeleteEndpointGroupWithContext mocks base method.
func (m *MockGlobalAccelerator) DeleteEndpointGroupWithContext(arg0 context.Context, arg1 *globalaccelerator.DeleteEndpointGroupInput) (*globalaccelerator.DeleteEndpointGroupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEndpointGroupWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.DeleteEndpointGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteEndpointGroupWithContext indicates an expected call of DeleteEndpointGroupWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) DeleteEndpointGroupWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEndpointGroupWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).DeleteEndpointGroupWithContext), arg0, arg1)
}

// DeleteListenerWithContext mocks base method.
func (m *MockGlobalAccelerator) DeleteListenerWithContext(arg0 context.Context, arg1 *globalaccelerator.DeleteListenerInput) (*globalaccelerator.DeleteListenerOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteListenerWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.DeleteListenerOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteListenerWithContext indicates an expected call of DeleteListenerWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) DeleteListenerWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteListenerWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).DeleteListenerWithContext), arg0, arg1)
}

// DescribeAcceleratorWithContext mocks base method.
func (m *MockGlobalAccelerator) DescribeAcceleratorWithContext(arg0 context.Context, arg1 *globalaccelerator.DescribeAcceleratorInput) (*globalaccelerator.DescribeAcceleratorOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeAcceleratorWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.DescribeAcceleratorOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeAcceleratorWithContext indicates an expected call of DescribeAcceleratorWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) DescribeAcceleratorWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeAcceleratorWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).DescribeAcceleratorWithContext), arg0, arg1)
}

// DescribeEndpointGroupWithContext mocks base method.
func (m *MockGlobalAccelerator) DescribeEndpointGroupWithContext(arg0 context.Context, arg1 *globalaccelerator.DescribeEndpointGroupInput) (*globalaccelerator.DescribeEndpointGroupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeEndpointGroupWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.DescribeEndpointGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeEndpointGroupWithContext indicates an expected call of DescribeEndpointGroupWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) DescribeEndpointGroupWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeEndpointGroupWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).DescribeEndpointGroupWithContext), arg0, arg1)
}

// DescribeListenerWithContext mocks base method.
func (m *MockGlobalAccelerator) DescribeListenerWithContext(arg0 context.Context, arg1 *globalaccelerator.DescribeListenerInput) (*globalaccelerator.DescribeListenerOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeListenerWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.DescribeListenerOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DescribeListenerWithContext indicates an expected call of DescribeListenerWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) DescribeListenerWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeListenerWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).DescribeListenerWithContext), arg0, arg1)
}

// ListAcceleratorsAsList mocks base method.
func (m *MockGlobalAccelerator) ListAcceleratorsAsList(arg0 context.Context, arg1 *globalaccelerator.ListAcceleratorsInput) ([]types.Accelerator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAcceleratorsAsList", arg0, arg1)
	ret0, _ := ret[0].([]types.Accelerator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAcceleratorsAsList indicates an expected call of ListAcceleratorsAsList.
func (mr *MockGlobalAcceleratorMockRecorder) ListAcceleratorsAsList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAcceleratorsAsList", reflect.TypeOf((*MockGlobalAccelerator)(nil).ListAcceleratorsAsList), arg0, arg1)
}

// ListEndpointGroupsAsList mocks base method.
func (m *MockGlobalAccelerator) ListEndpointGroupsAsList(arg0 context.Context, arg1 *globalaccelerator.ListEndpointGroupsInput) ([]types.EndpointGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEndpointGroupsAsList", arg0, arg1)
	ret0, _ := ret[0].([]types.EndpointGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEndpointGroupsAsList indicates an expected call of ListEndpointGroupsAsList.
func (mr *MockGlobalAcceleratorMockRecorder) ListEndpointGroupsAsList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEndpointGroupsAsList", reflect.TypeOf((*MockGlobalAccelerator)(nil).ListEndpointGroupsAsList), arg0, arg1)
}

// ListListenersAsList mocks base method.
func (m *MockGlobalAccelerator) ListListenersAsList(arg0 context.Context, arg1 *globalaccelerator.ListListenersInput) ([]types.Listener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListListenersAsList", arg0, arg1)
	ret0, _ := ret[0].([]types.Listener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListListenersAsList indicates an expected call of ListListenersAsList.
func (mr *MockGlobalAcceleratorMockRecorder) ListListenersAsList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListListenersAsList", reflect.TypeOf((*MockGlobalAccelerator)(nil).ListListenersAsList), arg0, arg1)
}

// ListListenersForAcceleratorWithContext mocks base method.
func (m *MockGlobalAccelerator) ListListenersForAcceleratorWithContext(arg0 context.Context, arg1 *globalaccelerator.ListListenersInput) (*globalaccelerator.ListListenersOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListListenersForAcceleratorWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.ListListenersOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListListenersForAcceleratorWithContext indicates an expected call of ListListenersForAcceleratorWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) ListListenersForAcceleratorWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListListenersForAcceleratorWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).ListListenersForAcceleratorWithContext), arg0, arg1)
}

// ListTagsForResourceWithContext mocks base method.
func (m *MockGlobalAccelerator) ListTagsForResourceWithContext(arg0 context.Context, arg1 *globalaccelerator.ListTagsForResourceInput) (*globalaccelerator.ListTagsForResourceOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTagsForResourceWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.ListTagsForResourceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTagsForResourceWithContext indicates an expected call of ListTagsForResourceWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) ListTagsForResourceWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsForResourceWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).ListTagsForResourceWithContext), arg0, arg1)
}

// TagResourceWithContext mocks base method.
func (m *MockGlobalAccelerator) TagResourceWithContext(arg0 context.Context, arg1 *globalaccelerator.TagResourceInput) (*globalaccelerator.TagResourceOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagResourceWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.TagResourceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TagResourceWithContext indicates an expected call of TagResourceWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) TagResourceWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagResourceWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).TagResourceWithContext), arg0, arg1)
}

// UntagResourceWithContext mocks base method.
func (m *MockGlobalAccelerator) UntagResourceWithContext(arg0 context.Context, arg1 *globalaccelerator.UntagResourceInput) (*globalaccelerator.UntagResourceOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UntagResourceWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.UntagResourceOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UntagResourceWithContext indicates an expected call of UntagResourceWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) UntagResourceWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UntagResourceWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).UntagResourceWithContext), arg0, arg1)
}

// UpdateAcceleratorWithContext mocks base method.
func (m *MockGlobalAccelerator) UpdateAcceleratorWithContext(arg0 context.Context, arg1 *globalaccelerator.UpdateAcceleratorInput) (*globalaccelerator.UpdateAcceleratorOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAcceleratorWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.UpdateAcceleratorOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAcceleratorWithContext indicates an expected call of UpdateAcceleratorWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) UpdateAcceleratorWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAcceleratorWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).UpdateAcceleratorWithContext), arg0, arg1)
}

// UpdateEndpointGroupWithContext mocks base method.
func (m *MockGlobalAccelerator) UpdateEndpointGroupWithContext(arg0 context.Context, arg1 *globalaccelerator.UpdateEndpointGroupInput) (*globalaccelerator.UpdateEndpointGroupOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEndpointGroupWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.UpdateEndpointGroupOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateEndpointGroupWithContext indicates an expected call of UpdateEndpointGroupWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) UpdateEndpointGroupWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEndpointGroupWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).UpdateEndpointGroupWithContext), arg0, arg1)
}

// UpdateListenerWithContext mocks base method.
func (m *MockGlobalAccelerator) UpdateListenerWithContext(arg0 context.Context, arg1 *globalaccelerator.UpdateListenerInput) (*globalaccelerator.UpdateListenerOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateListenerWithContext", arg0, arg1)
	ret0, _ := ret[0].(*globalaccelerator.UpdateListenerOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateListenerWithContext indicates an expected call of UpdateListenerWithContext.
func (mr *MockGlobalAcceleratorMockRecorder) UpdateListenerWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateListenerWithContext", reflect.TypeOf((*MockGlobalAccelerator)(nil).UpdateListenerWithContext), arg0, arg1)
}
