// Code generated by MockGen. DO NOT EDIT.
// Source: sigs.k8s.io/aws-load-balancer-controller/pkg/aws/services (interfaces: Route53)

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	route53 "github.com/aws/aws-sdk-go-v2/service/route53"
	gomock "github.com/golang/mock/gomock"
)

// MockRoute53 is a mock of Route53 interface.
type MockRoute53 struct {
	ctrl     *gomock.Controller
	recorder *MockRoute53MockRecorder
}

// MockRoute53MockRecorder is the mock recorder for MockRoute53.
type MockRoute53MockRecorder struct {
	mock *MockRoute53
}

// NewMockRoute53 creates a new mock instance.
func NewMockRoute53(ctrl *gomock.Controller) *MockRoute53 {
	mock := &MockRoute53{ctrl: ctrl}
	mock.recorder = &MockRoute53MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoute53) EXPECT() *MockRoute53MockRecorder {
	return m.recorder
}

// ChangeRecordsWithContext mocks base method.
func (m *MockRoute53) ChangeRecordsWithContext(arg0 context.Context, arg1 *route53.ChangeResourceRecordSetsInput) (*route53.ChangeResourceRecordSetsOutput, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangeRecordsWithContext", arg0, arg1)
	ret0, _ := ret[0].(*route53.ChangeResourceRecordSetsOutput)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangeRecordsWithContext indicates an expected call of ChangeRecordsWithContext.
func (mr *MockRoute53MockRecorder) ChangeRecordsWithContext(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangeRecordsWithContext", reflect.TypeOf((*MockRoute53)(nil).ChangeRecordsWithContext), arg0, arg1)
}

// GetHostedZoneID mocks base method.
func (m *MockRoute53) GetHostedZoneID(arg0 context.Context, arg1 string) (*string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHostedZoneID", arg0, arg1)
	ret0, _ := ret[0].(*string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHostedZoneID indicates an expected call of GetHostedZoneID.
func (mr *MockRoute53MockRecorder) GetHostedZoneID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHostedZoneID", reflect.TypeOf((*MockRoute53)(nil).GetHostedZoneID), arg0, arg1)
}
