# The following patch adds a directive for certmanager to inject CA into the CRD
# CRD conversion requires k8s 1.13 or later.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    # `default` and `serving-cert` may be substituted by kustomize
    cert-manager.io/inject-ca-from: default/serving-cert
  name: targetgroupbindings.elbv2.k8s.aws
