package utils

const (
	// GatewayClassName is the default GatewayClass name generated by the migration tool.
	GatewayClassName = "aws-alb"

	// LBConfigAPIVersion is the APIVersion for gateway.k8s.aws CRDs (LoadBalancerConfiguration, TargetGroupConfiguration, etc).
	LBConfigAPIVersion = "gateway.k8s.aws/v1beta1"

	// TGConfigKind is the Kind for TargetGroupConfiguration.
	TGConfigKind = "TargetGroupConfiguration"

	// GatewayClassKind is the Kind for GatewayClass resources.
	GatewayClassKind = "GatewayClass"

	// MigrationTagKey is the AWS tag key used to track migration source.
	MigrationTagKey = "gateway.k8s.aws/migrated-from"

	// ProtocolHTTP is the HTTP protocol string used in listen-ports and ProtocolPort.
	ProtocolHTTP = "HTTP"

	// ProtocolHTTPS is the HTTPS protocol string used in listen-ports and ProtocolPort.
	ProtocolHTTPS = "HTTPS"

	// PlaceholderTLSSecretName is a placeholder Secret name used in Gateway HTTPS listener TLS config.
	// Gateway API requires certificateRefs for HTTPS listeners, but the ALB controller reads
	// the actual certificate from LoadBalancerConfiguration. This placeholder satisfies the webhook.
	PlaceholderTLSSecretName = "tls-secret"

	// LBCGatewayAPIGroup is the API group for LBC's Gateway API CRDs (LoadBalancerConfiguration, etc).
	LBCGatewayAPIGroup = "gateway.k8s.aws"

	// TargetGroupARNPrefix is the path segment in an ELB target group ARN that precedes the TG name.
	// ARN format: arn:aws:elasticloadbalancing:<region>:<account>:targetgroup/<name>/<id>
	TargetGroupARNPrefix = "targetgroup/"

	// ServicePortUseAnnotation is the magic port name that signals the backend
	// is defined by an actions.* annotation rather than a real K8s service.
	ServicePortUseAnnotation = "use-annotation"

	// TargetGroupNameBackendKind is the backendRef Kind recognized by the gateway
	// controller for referencing external target groups by name.
	TargetGroupNameBackendKind = "TargetGroupName"

	// ActionAnnotationPrefix is the full annotation key prefix for action annotations.
	ActionAnnotationPrefix = "alb.ingress.kubernetes.io/actions."

	// JSONFieldTargetGroupARN is the JSON field name for target group ARN in action annotations.
	JSONFieldTargetGroupARN = "targetGroupARN"

	// JSONFieldTargetGroupName is the JSON field name for target group name in action annotations.
	JSONFieldTargetGroupName = "targetGroupName"

	// WarnExternalTargetGroupMessage is the warning message for external target group references.
	WarnExternalTargetGroupMessage = `
		WARNING: Generated manifests reference external target groups (TargetGroupName/TargetGroupARN).
		External TGs can only be associated with one ALB at a time.
		Applying the Gateway manifests while the Ingress ALB is still active will fail.
		To migrate, either:
			1. Delete the Ingress rules referencing the external TG before applying Gateway manifests (cutover)
			2. Create a duplicate TG and update the generated Gateway manifest to use the new TG name`

	// TipUseFromClusterMessage is the tip shown when missing resources are detected.
	TipUseFromClusterMessage = `
		Tip: Use --from-cluster to automatically read all referenced resources,
			or include Service/IngressClass/IngressClassParams files in your input.
		`

	// WarnGroupOrderMessage is the warning shown when group.order is detected.
	WarnGroupOrderMessage = `
		WARNING: group.order annotation detected. Gateway API has no equivalent of group.order.
		Rule precedence will be determined by Gateway API definitions. Review generated HTTPRoutes to verify
		expected behavior matches current Ingress rule ordering.
		`

	// WarnCrossNamespaceGroupFormat is the warning format for cross-namespace groups.
	WarnCrossNamespaceGroupFormat = "WARNING: IngressGroup %q has members in different namespaces. " +
		"The generated Gateway uses allowedRoutes with From: All, which permits HTTPRoutes from any namespace " +
		"to attach. To restrict this, change From: All to From: Selector with a namespace label selector.\n"
)
