// Code generated by MockGen. DO NOT EDIT.
// Source: sigs.k8s.io/aws-load-balancer-controller/pkg/targetgroupbinding (interfaces: TargetsManager)

// Package targetgroupbinding is a generated GoMock package.
package targetgroupbinding

import (
	context "context"
	reflect "reflect"

	types "github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2/types"
	gomock "github.com/golang/mock/gomock"
	v1beta1 "sigs.k8s.io/aws-load-balancer-controller/apis/elbv2/v1beta1"
)

// MockTargetsManager is a mock of TargetsManager interface.
type MockTargetsManager struct {
	ctrl     *gomock.Controller
	recorder *MockTargetsManagerMockRecorder
}

// MockTargetsManagerMockRecorder is the mock recorder for MockTargetsManager.
type MockTargetsManagerMockRecorder struct {
	mock *MockTargetsManager
}

// NewMockTargetsManager creates a new mock instance.
func NewMockTargetsManager(ctrl *gomock.Controller) *MockTargetsManager {
	mock := &MockTargetsManager{ctrl: ctrl}
	mock.recorder = &MockTargetsManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTargetsManager) EXPECT() *MockTargetsManagerMockRecorder {
	return m.recorder
}

// DeregisterTargets mocks base method.
func (m *MockTargetsManager) DeregisterTargets(arg0 context.Context, arg1 *v1beta1.TargetGroupBinding, arg2 []types.TargetDescription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeregisterTargets", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeregisterTargets indicates an expected call of DeregisterTargets.
func (mr *MockTargetsManagerMockRecorder) DeregisterTargets(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeregisterTargets", reflect.TypeOf((*MockTargetsManager)(nil).DeregisterTargets), arg0, arg1, arg2)
}

// ListTargets mocks base method.
func (m *MockTargetsManager) ListTargets(arg0 context.Context, arg1 *v1beta1.TargetGroupBinding) ([]TargetInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTargets", arg0, arg1)
	ret0, _ := ret[0].([]TargetInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTargets indicates an expected call of ListTargets.
func (mr *MockTargetsManagerMockRecorder) ListTargets(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTargets", reflect.TypeOf((*MockTargetsManager)(nil).ListTargets), arg0, arg1)
}

// RegisterTargets mocks base method.
func (m *MockTargetsManager) RegisterTargets(arg0 context.Context, arg1 *v1beta1.TargetGroupBinding, arg2 []types.TargetDescription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterTargets", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterTargets indicates an expected call of RegisterTargets.
func (mr *MockTargetsManagerMockRecorder) RegisterTargets(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterTargets", reflect.TypeOf((*MockTargetsManager)(nil).RegisterTargets), arg0, arg1, arg2)
}
