name: "Dependency Review"
on:
  push:
    branches:
      - main
      - 'release-*'
  pull_request:
  workflow_dispatch:
    inputs:
      head_ref:
        description: 'HEAD git reference (tag/branch/commit) to analyze'
        required: true
        default: 'main'
        type: string
      base_ref:
        description: 'Base git reference (tag/branch/commit) to compare against head_ref'
        required: true
        default: 'main'
        type: string
permissions:
  contents: read
jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          show-progress: false
      - name: "Dependency Review"
        uses: actions/dependency-review-action@2031cfc080254a8a887f58cffee85186f0e49e48
        with:
          base-ref: ${{ inputs.base_ref || github.event.pull_request.base.sha || 'main' }}
          head-ref: ${{ inputs.head_ref || github.event.pull_request.head.sha || github.ref }}
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          show-progress: false
      - name: Setup Go Version
        run: echo "GO_VERSION=$(cat .go-version)" >> $GITHUB_ENV
      - id: govulncheck
        uses: golang/govulncheck-action@b625fbe08f3bccbe446d94fbf87fcc875a4f50ee
        with:
          go-version-input: ${{ env.GO_VERSION }}
          go-version-file: go.mod
